version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run:
          pip3 freeze
          name: Install pthon dependencies
          command:
            pip install --user -r requirments.txt
      - run:
          name: Run Unit Tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

